default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: timetracker
  password: vinsol

development:
  <<: *default
  database: TimeTracker_development
test:
  <<: *default
  database: TimeTracker_test

production:
  <<: *default
  database: TimeTracker_production

