# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 70e18adefbb216f5fb858a80f2c95a67a0f567c21b1c68dd4792753fcabacf3f06e88c90f38ccb13fcfe23d01be6106a8d49104a4a1c62d609e9988b3847d37a

test:
  secret_key_base: 791fd4c6303adf6858a48fe8d9af89e589fb9635a81ba90ac7b7b2b7d7a72171b5f0311b682d82dc4675313e0e161837affe7019782684d332302d98a9de660c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
